### ISSUE TITLE
Please switch to GA gRPC API in prediction_service_pb2_grpc.

### ISSUE THREAD

**Issue by testnobody** [ThoroughImages/PathologyGo#1]
tf_serving中的代码似乎与最新的安装环境不兼容，作者可否提供代码适合运行的环境信息，包括库的版本

**Comment by physicso** [comment]
可以使用我们编译好的1.3.0版本TF Serving
请见——
https://hub.docker.com/r/physicso/tf_serving_gpu
docker pull physicso/tf_serving_gpu:1.3.0

**Comment by testnobody** [comment]
感谢答复！
我尝试在我现有的环境中部署您的DOCKER容器（WIN10环境），但最终运行代码时仍提示错误如下。
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses"
        debug_error_string = "{"created":"@1603952949.067000000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":4090,"referenced_errors":[{"created":"@1603952949.067000000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":394,"grpc_status":14}]}"
>

我注意到您的config中对于TF serving的默认端口是9000，但是在桌面版的DOCKER中似乎无法映射您physicso/tf_serving_gpu:1.3.0镜像的任何端口，我不知目前的错误是否出于这个原因。😊
再次感谢你的答复

**Comment by physicso** [comment]
我们确实没在除Linux的其他环境中运行过这个镜像，建议您在Linux运行一下试试
